language: cpp

dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake libboost-all-dev libpcl-all
  - cmake --version

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make -j4
  - ctest -VV

notifications:
  email:
    on_success: change
    on_failure: change
