#!/bin/bash

CLANG_FORMAT=clang-format

declare -a dirs=("Executables"
                 "Libraries"
                 "imu/Teensy/src"
                 "imu/Teensy/lib/MSP"
                 "imu/Teensy/lib/Scheduler")

for d in "${dirs[@]}"
do
  echo "$d"
  find "$d" \( -name '*.h' -o -name '*.cpp' \) -print0 | xargs -0 "$CLANG_FORMAT" -i
done

